---
- name: Preconfig
  hosts: ubuntu
  tasks:

    - name: Install Docker
      block:

        - name: Add universe
          apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present
        
        - name: Install packages
          apt: 
            name: 
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
            update-cache: yes
            cache_valid_time: 86400

        - name: Add GPG KEY
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            keyring: /usr/share/keyrings/docker-archive-keyring.gpg
            state: present

        - name: Add repository
          apt_repository:
            repo: >
              deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] 
              https://download.docker.com/linux/ubuntu
              {{ ansible_distribution_release }} stable
            state: present
            update-cache: yes
            filename: docker

        - name: Install Docker-ce
          apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
            update-cache: yes
          
        - name: Check Docker status
          service:
            name: docker
            state: restarted
            enabled: yes

    - name: Install Docker-compose
      block:

        - name: Getting the latest version Docker-compose
          uri:
            url: https://api.github.com/repos/docker/compose/releases/latest
            body_format: json
          register: page

        - name: Install Docker-compose
          get_url:
            url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64"
            dest: /usr/local/bin/docker-compose
            mode: 0755

        - name: Create a symbolic link
          ansible.builtin.file:
            src: /usr/local/bin/docker-compose
            dest: /usr/bin/docker-compose
            state: link
    
    - name: Postconfig
      block:
        - name: Add user to group Docker
          user:
            name: "{{ ansible_user }}"
            groups: docker
            append: yes

